version: '3.2'

volumes:
  nc_app:
    driver_opts:
      type: nfs
      o: "addr=srv-storage,rw,nfsvers=4,nolock,soft,exec"
      device: ":/docker-volume/${STACK}/app"
  nc_db:
    driver_opts:
      type: nfs
      o: "addr=srv-storage,rw,nfsvers=4,nolock,soft,exec"
      device: ":/docker-volume/${STACK}/database"
  nc_app_data:
    driver_opts:
      type: nfs
      o: "addr=srv-storage,rw,nfsvers=4,nolock,soft,exec"
      device: ":/docker-data/${STACK}/data"


networks:
  nc_network:
  traefik_web:
    external: true

services:
  db:
    image: mariadb:v10.5.4
    networks:
      nc_network:
        aliases:
          - database
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - type: volume
        source: nc_db
        target: /var/lib/mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 256M
        reservations:
          cpus: '.5'
          memory: 256M
      labels:
        - "traefik.enable=false"
      placement:
        constraints: [node.role==worker]
    #env_file: /docker-config/nextcloud/config/nextcloud-db.env

  app:
    image: nextdrive:v19.0.2
    #image: nextcloud:v19.0.1
    networks:
      - traefik_web
      - nc_network
    depends_on:
      - "db"
    volumes:
      - type: volume
        source: nc_app
        target: /var/www/html
      - type: volume
        source: nc_app_data
        target: /var/www/html/data
      - /docker-config/nextcloud/custom_apps19:/var/www/html/custom_apps
      #- /docker-config/nextcloud/skeleton:/var/www/html/core/myskeleton
      - /docker-config/nextcloud/skeleton:/var/www/html/core/skeleton
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 256M
        reservations:
          cpus: '.5'
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.routers.${STACK}.rule=Host(`${STACK}.nextstep-it.com`)
        - traefik.http.routers.${STACK}.entrypoints=websecure
        - traefik.http.routers.${STACK}.tls.certresolver=myresolver
        - traefik.docker.network=traefik_web
        - traefik.http.services.${STACK}.loadbalancer.server.port=80
        #- traefik.http.routers.${STACK}.https.middlewares=onlyoffice-headers
        # HSTS
        - traefik.http.middlewares.nc-header.headers.referrerPolicy=no-referrer
        - traefik.http.middlewares.nc-header.headers.stsSeconds=31536000
        - traefik.http.middlewares.nc-header.headers.forceSTSHeader=true
        - traefik.http.middlewares.nc-header.headers.stsPreload=true
        - traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.nc-header.headers.browserXssFilter=true
        # Proxy
        - traefik.http.middlewares.${STACK}.headers.customrequestheaders.X-Forwarded-Proto=https
        # CalDav and CardDav
        - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
        - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
        - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
        # Attach middleware
        - traefik.http.routers.${STACK}.middlewares=nextcloud-caldav@docker,nc-header

      placement:
        constraints: [node.role==worker]
    #command: /ns_init_instance.sh
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
      NEXTCLOUD_TABLE_PREFIX: ${NEXTCLOUD_TABLE_PREFIX}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      NEXTCLOUD_UPDATE: ${NEXTCLOUD_UPDATE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      TZ: ${TZ}
      
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      NEXTCLOUD_TRUSTED_PROXIES: ${NEXTCLOUD_TRUSTED_PROXIES}
      NEXTCLOUD_OVERWRITEPROTOCOL: ${NEXTCLOUD_OVERWRITEPROTOCOL}
      NEXTCLOUD_OVERWRITEWEBROOT: ${NEXTCLOUD_OVERWRITEWEBROOT}
      NEXTDRIVE_OFFRE: ${NEXTDRIVE_OFFRE}
      NEXTDRIVE_OFFRE2: ${NEXTDRIVE_OFFRE2}
      
      STACK: ${STACK}
    #env_file: /docker-config/nextcloud/config/nextcloud-db.env 
  
  redis:
    image: redis:v6.0.8
    command: redis-server --requirepass P@assw0rd
    networks:
      nc_network:
        aliases:
          - ncredis
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 64M
        reservations:
          cpus: '.5'
          memory: 64M
      labels:
          - "traefik.enable=false"
      placement:
        constraints: [node.role==worker]

